# Generated by Django 5.1.5 on 2025-02-10 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_post_comments_alter_comment_post_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WallThumbnail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="wall_thumbnails/")),
                (
                    "wall",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thumbnails",
                        to="api.wall",
                    ),
                ),
            ],
        ),
    ]
