# Generated by Django 5.1.5 on 2025-01-23 22:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="comments",
            field=models.ManyToManyField(
                blank=True, related_name="comments_posts", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
