# Generated by Django 5.1.5 on 2025-02-14 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_wallthumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="other_res",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
